language: node_js
node_js: 'lts/*'
#缓存
cache: npm
#指定分支
branches:
  only:
  - master
#安装环境
install:
  - npm install
#执行构建
script:
  - npm run build
#推送发布
after_script:
  #推送至构建发布分支，以GithubPage展示
  #- cd ./dist
  #- git init
  #- git config user.name "${USER_NAME}"
  #- git config user.email "${USER_EMAIL}"
  #- git add .
  #- git commit -m "build with ci"
  #- git push --force --quiet "https://${test_token}@${GH_REF}" master:${P_BRANCH}
  #推送至七牛云
  # - echo $TRAVIS_BUILD_DIR  #/home/travis/build/cheneyweb/pwa-vue
  - cd ./ci
  - rm -f pagelist.txt
  - bucketName="parcel"
  - ./qshell account $AK $SK 457299596@qq.com
  - ./qshell listbucket2 $bucketName -o pagelist.txt
  - ./qshell batchdelete --force $bucketName -i pagelist.txt
  - ./qshell qupload ./qshell.conf